from PyQt5.QtWidgets import*
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1100, 820)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeview1 = QtWidgets.QTreeView(self.splitter)
        self.treeview1.setMinimumSize(QtCore.QSize(120, 200))
        self.treeview1.setMaximumSize(QtCore.QSize(320, 400))
        self.treeview1.setObjectName("treeWidget")
        self.treeview2 = QtWidgets.QTreeView(self.splitter)
        self.treeview2.setMinimumSize(QtCore.QSize(100, 100))
        self.treeview2.setMaximumSize(QtCore.QSize(300, 400))
        # self.treeWidget_2.setColumnCount(1)
        self.treeview2.setObjectName("treeWidget_2")
        # self.treeWidget_2.headerItem().setText(0, "公共资源")
        self.treeview2.header().setDefaultSectionSize(124)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(600, 300))
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        self.actionNewFile.setShortcutVisibleInContextMenu(False)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionBackToLastStep = QtWidgets.QAction(MainWindow)
        self.actionBackToLastStep.setObjectName("actionBackToLastStep")
        self.actionNextStep = QtWidgets.QAction(MainWindow)
        self.actionNextStep.setObjectName("actionNextStep")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAll = QtWidgets.QAction(MainWindow)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionExite = QtWidgets.QAction(MainWindow)
        self.actionExite.setObjectName("actionExite")
        self.actionKewWords = QtWidgets.QAction(MainWindow)
        self.actionKewWords.setObjectName("actionKewWords")
        self.actionUseDoc = QtWidgets.QAction(MainWindow)
        self.actionUseDoc.setObjectName("actionUseDoc")
        self.actionDisplayLogs = QtWidgets.QAction(MainWindow)
        self.actionDisplayLogs.setObjectName("actionDisplayLogs")
        self.actionDisplayReport = QtWidgets.QAction(MainWindow)
        self.actionDisplayReport.setObjectName("actionDisplayReport")
        self.actionQuickSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuickSave.setIcon(icon)
        self.actionQuickSave.setObjectName("actionQuickSave")
        self.actionLastStep = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/Knob Left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLastStep.setIcon(icon1)
        self.actionLastStep.setObjectName("actionLastStep")
        self.actionNextStep = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/Knob Forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNextStep.setIcon(icon2)
        self.actionNextStep.setObjectName("actionNextStep")
        self.actionRunCase = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/Knob Play Green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRunCase.setIcon(icon3)
        self.actionRunCase.setObjectName("actionRunCase")
        self.actionReRun = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/Knob Refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReRun.setIcon(icon4)
        self.actionReRun.setObjectName("actionReRun")
        self.actionScreenShot = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScreenShot.setIcon(icon5)
        self.actionScreenShot.setObjectName("actionScreenShot")
        self.menu.addAction(self.actionNewFile)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveAll)
        self.menu.addAction(self.actionExite)
        self.menu_2.addAction(self.actionBackToLastStep)
        self.menu_2.addAction(self.actionNextStep)
        self.menu_3.addAction(self.actionKewWords)
        self.menu_3.addAction(self.actionUseDoc)
        self.menu_3.addAction(self.actionDisplayLogs)
        self.menu_3.addAction(self.actionDisplayReport)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionQuickSave)
        self.toolBar.addAction(self.actionLastStep)
        self.toolBar.addAction(self.actionNextStep)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRunCase)
        self.toolBar.addAction(self.actionReRun)
        self.toolBar.addAction(self.actionScreenShot)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Funny"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNewFile.setText(_translate("MainWindow", "新建文件夹"))
        self.actionBackToLastStep.setText(_translate("MainWindow", "返回上一步"))
        self.actionNextStep.setText(_translate("MainWindow", "撤销"))
        self.actionOpen.setText(_translate("MainWindow", "打开文件夹"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSaveAll.setText(_translate("MainWindow", "保存全部"))
        self.actionExite.setText(_translate("MainWindow", "退出"))
        self.actionKewWords.setText(_translate("MainWindow", "关键字库"))
        self.actionUseDoc.setText(_translate("MainWindow", "使用说明"))
        self.actionDisplayLogs.setText(_translate("MainWindow", "显示日志"))
        self.actionDisplayReport.setText(_translate("MainWindow", "显示测试报告"))
        self.actionQuickSave.setText(_translate("MainWindow", "快速保存"))
        self.actionQuickSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionLastStep.setText(_translate("MainWindow", "上一步"))
        self.actionLastStep.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionNextStep.setText(_translate("MainWindow", "下一步"))
        self.actionNextStep.setShortcut(_translate("MainWindow", "Ctrl+Alt+Z"))
        self.actionRunCase.setText(_translate("MainWindow", "运行"))
        self.actionReRun.setText(_translate("MainWindow", "重新执行"))
        self.actionScreenShot.setText(_translate("MainWindow", "截屏"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widget= QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())